function opts = setting_mdnet_org(opts)
    
    opts = mdnet_get_opts('verbose', opts.verbose, ...
        'netFile', opts.netFile, 'useGpu', opts.useGpu, ...
        'inputSize', [107 107], 'numSamples', 256, ...
        'cropPadding', 16, 'updateBatchSize', 128, ...
        'updateBatchPos', 32, 'updateBatchNeg', 96, ...
        'updateNumPos', 50, 'updateNumNeg', 200, ...
        'updateMaxIters', 10, 'updateInterval', 10, ... 
        'initLr', 0.0001, 'updateLr', 0.0003, ...
        'scale_f', 1, 'trans_f', 0.6);
    
    opts.state_initialize = @mdnet_state_initialize;
    opts.initialize = @mdnet_initialize;
    opts.track = @mdnet_track;
    opts.update = @mdnet_update;
end